name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          persist-credentials: false
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          otp-version: "26.0.2"
          gleam-version: "0.33.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
